### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by m4b** [endeav0r/falcon#22]
Wanted to try this out (nice work btw!)

Do you have a simple cli program that takes a binary as input and outputs whatever?

If not, I'd suggest adding a simple prototype/reference program in `lib/bin/main.rs` so could be easy to try out, or perhaps something in `examples/`

Keep up the good work!

**Comment by endeav0r** [comment]
I'm working on a blog post as we speak that will walk through all of this. I have been trying to do a weekly post on Falcon at http://reversing.io .

A lot of improvements have been dropped in during the past week while I work through the Palindrome challenge from CGC. None of that is in this repository, as I normally use Falcon as a 3rd party library (which you are correct, I should provide examples).

Give me a couple hours to flush out that blog post. I'll add a new comment and link it here which should send you a notification.

**Comment by m4b** [comment]
Cool ! No rush, take your time :)

**Comment by endeav0r** [comment]
And here we go :)

http://reversing.io/posts/2017-08-12/

This makes use of the example repository found here:

https://github.com/endeav0r/falcon-palindrome
